services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:php8.4-apache
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
      - ../frontend/:/var/www/html/wp-content/plugins/zeitraffer:ro
      - ../videos/:/var/www/html/wp-content/zeitraffer-videos/:ro

volumes:
  wordpress:
  db:
